update poi set description = "" where id=1;
update poi set description = "" where id=2;
update poi set description = "" where id=3;
update poi set description = "It is consider one of the principals elements of the mission, place where was realized all type of creatives activities and cultural. It has a cross, in the center the Patron Saint from the place 'The Divine Jesus Child'." where id=4;
update poi set description = "The frontage present a mixtilinear arc, called in this way form present rectilinear segments in the curve. It repose on mensula and forms the three vains of access of the frontage of the church." where id=5;
update poi set description = "They are situed between the three access of the frontage and has a garlands decoration topped with papals shields. " where id=6;
update poi set description = "They are situed between the three access of the frontage and has a garlands decoration topped with papals shields." where id=7;
update poi set description = "They divide the principal nave of the laterals. They are more than one meter and a half of thickness and stayed unfinished a few meters from the height." where id=8;
update poi set description = "They divide the principal nave of the laterals. They are more than one meter and a half of thickness and stayed unfinished a few meters from the height." where id=9;
update poi set description = "The stipes: Are the pilasters of pyramidal form inverted that carry a coating clear color and they separate the doors and windows articulating the naves interior." where id=10;
update poi set description = "The first stretch of the tower was vaulted and used to celebrate the baptism. Actually it this the one covered interior of the church." where id=11;
update poi set description = "The first stretch of the tower was vaulted and used to celebrate the baptism. Actually it this the one covered interior of the church." where id=12;
update poi set description = "The base to the pulpits: they are introduced in the two pillars in both sides from the principal nave." where id=13;
update poi set description = "The base to the pulpits: they are introduced in the two pillars in both sides from the principal nave." where id=14;
update poi set description = "" where id=15;
update poi set description = "It was in work process. It would have been ornamented with a piece of wood that would keep the images. " where id=16;
update poi set description = "The Covers Sacristia: They give an access from the Presbytery and are decorated with arc of curtain and finished herreriana inspiration. In the booth we could appreciate orifices where were the wood beams that hold up tiles ceiling." where id=17;
update poi set description = "The Covers Sacristia: They give an access from the Presbytery and are decorated with arc of curtain and finished herreriana inspiration. In the booth we could appreciate orifices where were the wood beams that hold up tiles ceiling." where id=18;
update poi set description = "A lot of angels and garlands of flowers. The drain is in the wall and in the floor that worked as heating system in the winter. " where id=19;
update poi set description = "" where id=20;
update poi set description = "" where id=21;
update poi set description = "" where id=22;
update poi set description = "It is located south of the edifice behind the gallery, here lead the canal of drain and there is reused the rain water for irrigation of crops." where id=23;
update poi set description = "Located east side of the temple, it was not reached." where id=24;
update poi set description = "Place where was extracted the stones for the edification, is located about one thousand meters from the place." where id=25;
update poi set description = "It is attached to the Sacristy and has a long arcaded gallery of pillars. It became  ceiling and the windows still we can be observe the holes that indicate the existence of iron bars." where id=26;
update poi set description = "" where id=27;
update poi set description = "" where id=28;
update poi set description = "" where id=29;
update poi set description = "" where id=30;
update poi set description = "" where id=31;
update poi set description = "" where id=32;
update poi set description = "" where id=33;
update poi set description = "The square is the center of the reduction and social life, place of meeting people. Here all activities are developed, were performed collective marriages, the music festivals and in sports different activities." where id=34;
update poi set description = "They are located around the main square, the block or "apple" comprised six to eight square pieces with sides ranging from five to six meters; in Trinidad were built with stone walls sandstone type YTAKY whose wards are surrounded by beautiful galleries (Jere corridor) with arches in the Roman style." where id=35;
update poi set description = "" where id=36;
update poi set description = "Built around 1740 by architect Juan Bautista Prímoli; Brother Coadjutor of the Society of Jesus, built of ashlars stone, composed within a central nave and two bays side; had three vaults half and a central dome, also has a good decoration." where id=37;
update poi set description = "Image of San Pablo: He was found in archaeological excavations without having suffered or fragmentation. The Gargoyle: Gargoyle of a flying fish." where id=38;
update poi set description = "Lithic remains found upon entering the main temple." where id=39;
update poi set description = "Its carved in 1720, is in the left aisle of the main temple ornamented with designs inspired by the vegetation of the area and at the bottom designs the words Father, Son and Holy Spirit (in Latin) which are the words of welcome to Christianity is displayed." where id=40;
update poi set description = "It lies at the foot of the right of the main temple lateral sector has an altar where the deceased was deposited before being buried to fulfill religious rituals .This is an altar with an altarpiece half Spanish and half Italian, but whose reliefs highlighted the oblique light from the side door, the unmistakable imprint of Guarani carver who worked with special motivation in one of the deepest issues of their ancestral tradition; the ancestor worship at the altar of the 'animas and the doctrine of the purification of souls, after the ascent to heaven." where id=41;
update poi set description = "Located in the main nave of the main temple. (1765) This lytic structure was found in over a thousand fragments during archaeological excavations. It is the only piece that was totally restored and mounted in its place of origin, was used for the homilies. Carved stone polychrome and gilded leaf; is observed at the top representing the four evangelists, the eagle represents San Juan, the bull to San Lucas, the angel to San Mateo and the lion to San Marcos. Haved various colors and sheets of gold and silver." where id=42;
update poi set description = "They are in the central part of main temple and is still displayed signs in some." where id=43;
update poi set description = "This sector of the temple is richly ornamented with reliefs, frames and hornacinas, mostly representing the vegetation of the area." where id=44;
update poi set description = "It is located in the center of the main temple, where should be put to the priests who were killed in the mission." where id=45;
update poi set description = "Located one on each side of the end of the main temple bearing the name of 'Sacristy Major and Minor and in some missions had a Contra sacristy'" where id=46;
update poi set description = "Ornamentation located in the upper part of the Presbytery angels observed with string instruments, wind and percussion." where id=47;
update poi set description = "Located on the west wall and east, garden with ornate door of the sacristy and frieze. At the top of the boot dome is seen Presbytery." where id=48;
update poi set description = "The cloister is comprised of the following: Rooms of the Priests, School, Workshops" where id=49;
update poi set description = "Located adjacent to the right Sacristy built with stone basaltic origin" where id=50;
update poi set description = "These classrooms were built with two types of materials (stone-adobe) on the floor difference is also observed an account with octagonal polychrome glazed bricks and others." where id=51;
update poi set description = "In this sector the bells were made for all the Jesuit missions." where id=52;
update poi set description = "This place was used for monitoring the safety of this mission, had bells to alert the people the threat of invasion." where id=53;
update poi set description = "This place was used for liturgical activities in the first period room of this mission, while the main temple was built. As was the custom of the Jesuits is accompanied by the cemetery; where buried the common Indians." where id=54;
update poi set description = "" where id=55;
update poi set description = "It is located near the early church, are vestiges where the first homes were located parental Mission residents of Trinidad. Today there are only bases and in the future should receive archaeological excavations." where id=56;
update poi set description = "It is an area located behind the Temple Mayor Mission, where it was cultivated for community support call the 'Tupa mba´e', property of God and was intended to orphaned children, single women and elderly people." where id=57;
update poi set description = "The Jesuit missions had their cemetery almost always on the side of their churches, Trinity two churches possessed and was intended for ordinary people, because the crypt was destined for the Jesuits and members caciques of the council were buried in the center the temple." where id=58;
update poi set description = "Prisons to be had in the Jesuit Missions were more committed to the punishment and after to avoid the bad habit of capital punishment practiced before the Jesuit missions faults." where id=59;
update poi set description = "Old road used to move from one mission to another to transport their products to places where they practiced barter exchange of products for use in their communities." where id=60;
update poi set description = "" where id=61;
update poi set description = "It is intended for reception of visitors, where you can buy tickets to the mission, access to a small room cyber room, image projection, interpretive room made of stone pieces, old photos and a model of the mission, and health services and administrative area. It is open from 7:00 to 19:00 pm. Monday to Sunday, extending the hours from Thursday to Sunday until 22:00 pm. for the event of Lights and Sounds." where id=62;