update poi set descricao = "" where id=1;
update poi set descricao = "" where id=2;
update poi set descricao = "" where id=3;
update poi set descricao = "Foi um elemento principal da missão. Nesse lugar a gente realizava todo tipo de atividade esportiva e cultural. Tem uma cruz em cada angulo e no centro o Santo Patrono: ‘A Divina Criança Jesus’." where id=4;
update poi set descricao = "A fachada tem uns arcos mixtilineos, chamados assim por ter segmentos retilíneos na sua curva. Descansam na cima de mísulas e Forman os vaus de aceso da fachada da igreja." where id=5;
update poi set descricao = "Estão entre os três acesos da fachada e levam uma decoração de guirnaldas rematadas com escudos papais." where id=6;
update poi set descricao = "Estão entre os três acesos da fachada e levam uma decoração de guirnaldas rematadas com escudos papais." where id=7;
update poi set descricao = "Dividem a nave principal das laterais. Som de mais de metro e meio groso e quedarem sem finalizar a poucos metros de altura." where id=8;
update poi set descricao = "Dividem a nave principal das laterais. Som de mais de metro e meio groso e quedarem sem finalizar a poucos metros de altura." where id=9;
update poi set descricao = "Os Estípites: som as pilastras de forma de pirâmide invertida que levam revestimento de cor claro e divide as portas e janela articulando o interior das naves." where id=10;
update poi set descricao = "A primeira parte da torre foi abovedada e utilizado para celebrar o batismo. Agora é o único interior coberto da igreja." where id=11;
update poi set descricao = "A primeira parte da torre foi abovedada e utilizado para celebrar o batismo. Agora é o único interior coberto da igreja." where id=12;
update poi set descricao = "A base para os púlpitos: Estão compostos em dois pilares em cada parte da nave principal." where id=13;
update poi set descricao = "A base para os púlpitos: Estão compostos em dois pilares em cada parte da nave principal." where id=14;
update poi set descricao = "" where id=15;
update poi set descricao = "Se achavam em processo de trabalho a ornamentação do retablo, iria ser ornamentada com um retablo de madeira que contenderia as imagens." where id=16;
update poi set descricao = "As portadas da sacristia: É o aceso do presbitério e está decorado com um arco em cortina e remates de inspiração herreriana, nas duas sacristias se pode olhar o arranque e os orifícios onde no seu momento se achavam as vigas de madeira que sustentam o teto de teia." where id=17;
update poi set descricao = "As portadas da sacristia: É o aceso do presbitério e está decorado com um arco em cortina e remates de inspiração herreriana, nas duas sacristias se pode olhar o arranque e os orifícios onde no seu momento se achavam as vigas de madeira que sustentam o teto de teia." where id=18;
update poi set descricao = "Uma grande venera orlada de anjos e guirnaldas de flores. O deságüe vão impetrado no muro e nos pisos, fazia um sistema de calefação no inverno." where id=19;
update poi set descricao = "" where id=20;
update poi set descricao = "" where id=21;
update poi set descricao = "" where id=22;
update poi set descricao = "Se acham no sul do edifício depois da galeria, neste sitio tem a desembocadura do canal de deságüe e ali se reutilizava a água da chuva para os cultivos." where id=23;
update poi set descricao = "Estava no lado este da igreja, não se chego a constituir." where id=24;
update poi set descricao = "Ali se pegavam as pedras para a edificação. Acham-se uns 1000 metros do lugar." where id=25;
update poi set descricao = "Adotado a sacristia, tem uma grande galeria com pilares ochavados. Chegou a ter teto e nas janelas se podem olhar as aberturas que indicam a existência de rejas de ferro." where id=26;
update poi set descricao = "" where id=27;
update poi set descricao = "" where id=28;
update poi set descricao = "" where id=29;
update poi set descricao = "" where id=30;
update poi set descricao = "" where id=31;
update poi set descricao = "" where id=32;
update poi set descricao = "" where id=33;
update poi set descricao = "A praça centro da redução e a vida social, lugar de reunião do povo. Suas dimensões som a mesma em cada parte: mínimo cem metros de ancho e cento trinta de largo. Uma cruz monumental se levantava com uma estatua da virgem a maioria das vezes e outra do mesmo santo patrono da cidade. Neste lugar se levavam a cabo todas as atividades na parte social os casamentos coletivos e no cultural os festivais de musica e no esportivo os diferentes tipos de atividades." where id=34;
update poi set descricao = "Se acham perto da praça maior, tem um sistema de broques de casas divididas por umas paredes para cada família núcleo. O broque o quarteirão estava composto por seis a oito dormitórios quadrados com lados de cinco a seis metros, em Trinidad se fizeram as paredes de pedras areníticas YTAKY com corredores com galerias (corredor jere) com arcos de médio ponto com estilo romano." where id=35;
update poi set descricao = "" where id=36;
update poi set descricao = "Foi construído por o ano 1740 pelo arquiteto Juan Bautista Primoli, irmão coadjutor do povo de Jesus, construída com pedras de seleira composta no seu interior por uma nave central e dois laterais; possuía três câmaras de media laranja e uma cúpula central, ademais possuía uma boa ormanentação." where id=37;
update poi set descricao = "Imagem de São Paulo. Foi achado nas escavações arqueológicas sem ter nenhuma fragmentação (1760 - 1767). A Gárgula: Gárgula de pez voador. (1765)" where id=38;
update poi set descricao = "Restos líticos que se acham na frente do templo maior nos lados do aceso principal da igreja." where id=39;
update poi set descricao = "Foi feita em 1720, se acha na nave lateral esquerda do templo maior ornamentada com desejos inspirados na vegetação da zona e na parte inferior se olha as palavras Padre, Filho e o Espírito Santo que som as palavras de bem-vinda ao cristão." where id=40;
update poi set descricao = "Se acha ao pé da parte lateral direita do templo maior. Tem um altar onde se colocava a os mortos para cumprir com os rituais religiosos. É um altar com um retablo metade espanhola e metade italiana, mas os releveis mostram a luz rasante da porta lateral. Os guaranis trabalhavam com especial motivação em uns de os temas mais arraigados da sua tradição ancestral: O culto de os antepassados no altar das animas e na doutrina da purificação das almas, previa no ascenso do paraíso." where id=41;
update poi set descricao = "Se acha na nave principal do templo maior. (1765) A estrutura lítica foi achada em mais de mil partes durante as escavações. É a única restaurada na sua totalidade e colocada em seu lugar de origem. Fui utilizada nas homilías. Talão em pedra policroma da e dourada na folha; na parte superior se olha a representação de os quatro evangelistas, o águia representa a São Juan, o toro São Lucas, o anjo São Mateo e o leão São Marcos. Possuía muitos cores y tambén láminas de oro e prata." where id=42;
update poi set descricao = "Se acha na parte central do templo maior e se olha ainda os signos em algumas de elas. " where id=43;
update poi set descricao = "Se acha ornamentado com releveis, recuados e hornacinas, em sua maioria representa a vegetação da zona. " where id=44;
update poi set descricao = "Se acha no centro do templo maior, onde os sacerdotes mortos na missão eram levados. " where id=45;
update poi set descricao = "Se acham uma de cada lado da parte última do templo maior levando o nome de Sacristia maior e menor e em algumas missões existia uma Contra Sacristia." where id=46;
update poi set descricao = "Ornamentação que se acha na parte superior do Presbitério, se olha anjos com instrumentos de corda, vento e percuto, também está à representação da imaculada." where id=47;
update poi set descricao = "Se acha na parede este e oeste  com ornamentações da porta das sacristias e friso. Na parte superior se olha o arranque da bovídea do Presbitério." where id=48;
update poi set descricao = "Na parte direita por fora do templo fica o Claustro. Composto por habitações de sacerdotes, aula do colégio e os talheres." where id=49;
update poi set descricao = "Fica contiguamente da sacristia direita, feita com pedras basálticas." where id=50;
update poi set descricao = "As aulas foram feitas com pedras e com abobe. No piso também de olha a diferença de materiais de ladrilhos octogonais com policromia vitrificada." where id=51;
update poi set descricao = "Nesta parte se faziam as campanas para todas as reduções. " where id=52;
update poi set descricao = "Nesta parte foram utilizadas para o controle da seguridade desta missão, as campanas eram para alertar ao povo da amenas de invasão. " where id=53;
update poi set descricao = "Nesta parte se fazia as atividades litúrgicas no primeiro período da missão e ainda se construía o templo maior. Perto fica o cemitério, costume dos jesuítas, onde se enterravam os indígenas comuns. " where id=54;
update poi set descricao = "" where id=55;
update poi set descricao = "Se acha perto da igreja primitiva, som vestígios onde ficavam as primeiras casas de os pais que moravam na missão de Trinidad Hoje ficam só as bases e em um  futuro deveria de Haber escavações arqueológicas. " where id=56;
update poi set descricao = "Fica detrais do templo maior da missão onde se cultivada para o sustento da comunidade, chamado o Tupa mba'e(Propriedade de Deus) e era para as crianças ufanas e mulheres sozinhas e pessoas maiores. Ademais também havia cultivos para cada família, uma parcela de terra destinada a cultivo chamado ‘Tupa mbae’ propriedade do índio o nativo." where id=57;
update poi set descricao = "Os cemitérios das missões jesuíticas quase sempre ficavam ao costado das igrejas. Em Trinidad as igrejas teriam assim e a povo comum as usava, mas os sacerdotes usavam a cripta e os caciques membros do cabido eram enterrados no centro do templo. " where id=58;
update poi set descricao = "Os cárceres que possuíam as missões eram mais para o castigo por faltas cometidas para não fazer a pena capital praticado antes das missões." where id=59;
update poi set descricao = "Rua velha utilizada para ir de uma missão para outra, para levar seus produtos para os lugares onde se fazia truques por outros produtos para utilizar em sua comunidade. " where id=60;
update poi set descricao = "" where id=61;
update poi set descricao = "O centro serve para receber os turistas, onde a gente pode receber as entradas a missão. Tem uma sala cyber, sala de projeção de imagens, e um pequeno museu de peças antigas, imagens e maquetas de missão. Tem serviços sanitários e uma área administrativa. Esta aberta de 7:00 a 19:00 horas de segunda-feira a domingos e de quinta-feira a domingos até as 22:00 para o show de luz e sonido. " where id=62;