update poi set nome = "Museu" where id=1;
update poi set nome = "Mirante" where id=2;
update poi set nome = "Mirante" where id=3;
update poi set nome = "Praça" where id=4;
update poi set nome = "Fachada" where id=5;
update poi set nome = "Hornacina São Paulo" where id=6;
update poi set nome = "Hornacina São Pedro" where id=7;
update poi set nome = "Pilar" where id=8;
update poi set nome = "Pilar" where id=9;
update poi set nome = "Templo" where id=10;
update poi set nome = "Torre" where id=11;
update poi set nome = "Torre" where id=12;
update poi set nome = "Púlpito" where id=13;
update poi set nome = "Púlpito" where id=14;
update poi set nome = "Pilates" where id=15;
update poi set nome = "Altar Maior" where id=16;
update poi set nome = "Sacristia" where id=17;
update poi set nome = "Sacristia" where id=18;
update poi set nome = "Igreja Secondaria ou Prebistero" where id=19;
update poi set nome = "Fonte da agua" where id=20;
update poi set nome = "Corredor Jere" where id=21;
update poi set nome = "Residência" where id=22;
update poi set nome = "Horta Comunitária" where id=23;
update poi set nome = "Cemitério" where id=24;
update poi set nome = "Pedreira" where id=25;
update poi set nome = "Escola" where id=26;
update poi set nome = "Sala de Jantar e Cozinha" where id=27;
update poi set nome = "Estoque" where id=28;
update poi set nome = "Workshops" where id=29;
update poi set nome = "Claustros" where id=30;
update poi set nome = "Sala de Aula espiritual" where id=31;
update poi set nome = "Galeria de Casas" where id=32;
update poi set nome = "Galeria de Casas" where id=33;
update poi set nome = "Praça Maior" where id=34;
update poi set nome = "Casa dos indígenas" where id=35;
update poi set nome = "Casa dos indígenas" where id=36;
update poi set nome = "Templo Maior" where id=37;
update poi set nome = "Atrio do templo maior" where id=38;
update poi set nome = "Pila de Santiguação" where id=39;
update poi set nome = "Pila bautismal" where id=40;
update poi set nome = "Altar das almas do purgatório" where id=41;
update poi set nome = "Púlpito" where id=42;
update poi set nome = "Museu Lítico" where id=43;
update poi set nome = "Muro Lateral" where id=44;
update poi set nome = "Cripta" where id=45;
update poi set nome = "Sacristias" where id=46;
update poi set nome = "Friso dos Ánjos Músicos" where id=47;
update poi set nome = "Portal da sacristia" where id=48;
update poi set nome = "Claustros" where id=49;
update poi set nome = "Residência para sacerdotes" where id=50;
update poi set nome = "Salas da aula da escola" where id=51;
update poi set nome = "Workshops" where id=52;
update poi set nome = "Torre Atalaya ou torre de vigia" where id=53;
update poi set nome = "Templo Primitivo" where id=54;
update poi set nome = "Basamento-Antigo Pilar de Pedra" where id=55;
update poi set nome = "Sítio Arqueológico" where id=56;
update poi set nome = "Pomar" where id=57;
update poi set nome = "Cemitério" where id=58;
update poi set nome = "Prisão" where id=59;
update poi set nome = "Tape Tuja" where id=60;
update poi set nome = "Artes" where id=61;
update poi set nome = "Centro de Informações Turísticas" where id=62;